from argparse import ArgumentParser, BooleanOptionalAction

from ct_pipeline.config import add_ct_model_args, add_ct_optimization_args
from ct_pipeline.training.presets import CTTrainingArgumentParser, available_ct_training_presets

from .defaults import *


def build_parser() -> ArgumentParser:
    parser = CTTrainingArgumentParser(description="CT training script parameters")
    add_ct_model_args(parser)
    add_ct_optimization_args(parser)
    parser.add_argument(
        "--ct_preset",
        choices=available_ct_training_presets(),
        default=None,
        help="Apply a named CT training recipe before explicit CLI overrides.",
    )
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument("--checkpoint_iterations", nargs="+", type=int, default=[])
    parser.add_argument("--start_checkpoint", type=str, default=None)
    parser.add_argument("--save_iterations", nargs="+", type=int, default=[7_000, 30_000])
    parser.add_argument("--load_ply", action="store_true", default=False)
    parser.add_argument("--wandb", action="store_true", default=False)
    parser.add_argument("--ct_phase1_dir", type=str, default=None)
    parser.add_argument("--ct_volume_path", type=str, default=None)
    parser.add_argument("--ct_volume_format", type=str, default="auto", choices=["auto", "dicom", "raw", "tiff"])
    parser.add_argument("--ct_raw_meta", type=str, default=None)
    parser.add_argument("--ct_bulk_boundary_margin_voxels", type=int, default=1)
    parser.add_argument("--ct_support_sample_count", type=int, default=None)
    parser.add_argument("--ct_air_sample_count", type=int, default=None)
    parser.add_argument("--ct_volume_sample_count", type=int, default=4096)
    parser.add_argument("--ct_volume_jitter", "--ct_volume_jitter_voxels", dest="ct_volume_jitter", type=float, default=CT_VOLUME_JITTER)
    parser.add_argument("--ct_boundary_band", "--ct_boundary_band_voxels", dest="ct_boundary_band", type=float, default=CT_BOUNDARY_BAND)
    parser.add_argument("--ct_surface_boundary_sample_ratio", type=float, default=0.5)
    parser.add_argument("--ct_lambda_volume", type=float, default=1.0)
    parser.add_argument("--ct_lambda_occupancy", type=float, default=1.0)
    parser.add_argument("--ct_surface_regularizer_weight", type=float, default=0.5)
    parser.add_argument("--ct_training_mode", type=str, default=CT_TRAINING_MODE,
                        choices=["default", "role_separated_joint"],
                        help="Training mode: default (current) or role_separated_joint (Method C)")
    parser.add_argument("--ct_bulk_adaptive_mode", type=str, default=CT_BULK_ADAPTIVE_MODE,
                        choices=["fixed", "scale", "scale_offset"],
                        help="Bulk geometry adaptation: fixed (geometry frozen) | scale (trainable 蟽) | scale_offset (蟽 + bounded 螖p)")
    parser.add_argument("--ct_bulk_sigma_min_mm", type=float, default=CT_BULK_SIGMA_MIN_MM,
                        help="Min bulk sigma in world mm (0 = no clamp). E.g. 0.10 for bunny (spacing=0.39mm)")
    parser.add_argument("--ct_bulk_sigma_max_mm", type=float, default=CT_BULK_SIGMA_MAX_MM,
                        help="Max bulk sigma in world mm (large = no clamp). E.g. 1.5 for bunny")
    parser.add_argument("--ct_bulk_scale_anchor_weight", type=float, default=CT_BULK_SCALE_ANCHOR_WEIGHT)
    parser.add_argument("--ct_bulk_pos_anchor_weight", type=float, default=CT_BULK_POS_ANCHOR_WEIGHT)
    # role_separated_joint config
    parser.add_argument("--ct_surface_phase_loss_weight", type=float, default=1.0)
    parser.add_argument("--ct_surface_phase_margin_vox", type=float, default=0.5,
                        help="Margin in voxels for surface phase loss (inside/outside pushes)")
    parser.add_argument("--ct_surface_phase_temp_vox", type=float, default=0.1,
                        help="Softplus temperature for phase loss")
    parser.add_argument("--ct_surface_normal_smooth_weight", type=float, default=0.05)
    parser.add_argument("--ct_surface_anchor_weight", type=float, default=0.01)
    # confidence map config
    parser.add_argument("--ct_confidence_mode", type=str, default="auto_percentile",
                        choices=["auto_percentile", "static_threshold"])
    parser.add_argument("--ct_conf_material_threshold", type=float, default=None)
    parser.add_argument("--ct_conf_air_threshold", type=float, default=None)
    parser.add_argument("--ct_conf_unknown_band_width", type=float, default=0.0)
    parser.add_argument("--ct_conf_min_component_size", type=int, default=500)
    parser.add_argument("--ct_use_unified_compositor", action=BooleanOptionalAction, default=CT_USE_UNIFIED_COMPOSITOR)
    parser.add_argument("--ct_dual_separated_training", action=BooleanOptionalAction, default=CT_DUAL_SEPARATED_TRAINING)
    parser.add_argument("--ct_bulk_halfspace_enable", action=BooleanOptionalAction, default=CT_BULK_HALFSPACE_ENABLE)
    parser.add_argument("--ct_bulk_halfspace_tau_init", type=float, default=CT_BULK_HALFSPACE_TAU_INIT)
    parser.add_argument("--ct_bulk_halfspace_tau_final", type=float, default=CT_BULK_HALFSPACE_TAU_FINAL)
    parser.add_argument("--ct_bulk_halfspace_tau_gate_threshold", type=float, default=CT_BULK_HALFSPACE_TAU_GATE_THRESHOLD)
    parser.add_argument("--ct_bulk_halfspace_tau_step", type=float, default=CT_BULK_HALFSPACE_TAU_STEP)
    parser.add_argument("--ct_bulk_halfspace_tau_update_interval", type=int, default=CT_BULK_HALFSPACE_TAU_UPDATE_INTERVAL)
    parser.add_argument("--ct_bulk_halfspace_skip_depth", type=float, default=CT_BULK_HALFSPACE_SKIP_DEPTH)
    parser.add_argument("--ct_exterior_air_sample_ratio", type=float, default=CT_EXTERIOR_AIR_SAMPLE_RATIO)
    parser.add_argument("--ct_bulk_volume_support_sample_ratio", type=float, default=CT_BULK_VOLUME_SUPPORT_SAMPLE_RATIO)
    parser.add_argument("--ct_surface_sigma_n_max", "--ct_surface_sigma_n_max_voxels", dest="ct_surface_sigma_n_max", type=float, default=CT_SURFACE_SIGMA_N_MAX)
    parser.add_argument("--ct_surface_sigma_t_min", "--ct_surface_sigma_t_min_voxels", dest="ct_surface_sigma_t_min", type=float, default=CT_SURFACE_SIGMA_T_MIN)
    parser.add_argument("--ct_surface_max_scale", "--ct_surface_max_scale_voxels", dest="ct_surface_max_scale", type=float, default=CT_SURFACE_MAX_SCALE)
    parser.add_argument("--ct_bulk_scale_adaptive_cap", action=BooleanOptionalAction, default=CT_BULK_SCALE_ADAPTIVE_CAP)
    parser.add_argument("--ct_bulk_scale_global_max", type=float, default=CT_BULK_SCALE_GLOBAL_MAX)
    parser.add_argument("--ct_bulk_scale_floor", type=float, default=CT_BULK_SCALE_FLOOR)
    # coverage-driven bulk sigma growth (geometry-grow phase): grow sigma to fill
    # material interior coverage; mask membership keeps it out of air/cavities.
    parser.add_argument("--ct_bulk_coverage_growth_weight", type=float, default=0.0)
    parser.add_argument("--ct_bulk_coverage_growth_sample_count", type=int, default=4096)
    parser.add_argument("--ct_bulk_coverage_growth_margin_vox", type=float, default=0.5)
    parser.add_argument("--ct_bulk_coverage_growth_scale_grad", type=float, default=1.0)
    parser.add_argument("--ct_bulk_coverage_growth_train_opacity", action=BooleanOptionalAction, default=False)
    # anti-leak: penalize UNGATED bulk density on void so the ungated display stays clean.
    parser.add_argument("--ct_bulk_void_leak_weight", type=float, default=0.0)
    parser.add_argument("--ct_bulk_void_leak_sample_count", type=int, default=4096)
    parser.add_argument("--ct_bulk_void_leak_margin_vox", type=float, default=0.5)
    parser.add_argument("--ct_surface_normal_weight", type=float, default=CT_SURFACE_NORMAL_WEIGHT)
    parser.add_argument("--ct_surface_thickness_weight", type=float, default=CT_SURFACE_THICKNESS_WEIGHT)
    parser.add_argument("--ct_surface_coverage_weight", type=float, default=CT_SURFACE_COVERAGE_WEIGHT)
    parser.add_argument("--ct_surface_coverage_sample_count", type=int, default=CT_SURFACE_COVERAGE_SAMPLE_COUNT)
    parser.add_argument("--ct_surface_coverage_target", type=float, default=CT_SURFACE_COVERAGE_TARGET)
    parser.add_argument("--ct_surface_coverage_until_iter", type=int, default=CT_SURFACE_COVERAGE_UNTIL_ITER)
    parser.add_argument("--ct_surface_material_gate_sigma", type=float, default=CT_SURFACE_MATERIAL_GATE_SIGMA)
    parser.add_argument("--ct_surface_material_delta", type=float, default=CT_SURFACE_MATERIAL_DELTA)
    parser.add_argument("--ct_surface_material_tau", type=float, default=CT_SURFACE_MATERIAL_TAU)
    parser.add_argument("--ct_surface_material_render_weight", type=float, default=CT_SURFACE_MATERIAL_RENDER_WEIGHT)
    parser.add_argument("--ct_surface_intensity_weight", type=float, default=CT_SURFACE_INTENSITY_WEIGHT)
    parser.add_argument("--ct_surface_intensity_sample_count", type=int, default=CT_SURFACE_INTENSITY_SAMPLE_COUNT)
    parser.add_argument("--ct_surface_intensity_material_ratio", type=float, default=CT_SURFACE_INTENSITY_MATERIAL_RATIO)
    parser.add_argument("--ct_dual_surface_inner_band", type=float, default=CT_DUAL_SURFACE_INNER_BAND)
    parser.add_argument("--ct_dual_surface_air_band", type=float, default=CT_DUAL_SURFACE_AIR_BAND)
    parser.add_argument("--ct_dual_soft_sigma", type=float, default=CT_DUAL_SOFT_SIGMA)
    parser.add_argument("--ct_dual_surface_air_sample_ratio", type=float, default=CT_DUAL_SURFACE_AIR_SAMPLE_RATIO)
    parser.add_argument("--ct_bulk_renderer_epsilon", type=float, default=CT_BULK_RENDERER_EPSILON)
    parser.add_argument("--ct_bulk_renderer_tau", type=float, default=CT_BULK_RENDERER_TAU)
    parser.add_argument("--ct_material_compose_mode", choices=["surface_first", "bulk_first_material"], default=CT_MATERIAL_COMPOSE_MODE)
    parser.add_argument("--ct_bulk_semantic_weight", type=float, default=CT_BULK_SEMANTIC_WEIGHT)
    parser.add_argument("--ct_bulk_semantic_sample_count", type=int, default=CT_BULK_SEMANTIC_SAMPLE_COUNT)
    parser.add_argument("--ct_bulk_semantic_focal_gamma", type=float, default=CT_BULK_SEMANTIC_FOCAL_GAMMA)
    parser.add_argument("--ct_bulk_semantic_epsilon", type=float, default=CT_BULK_SEMANTIC_EPSILON)
    parser.add_argument("--ct_bulk_semantic_pos_ratio", type=float, default=CT_BULK_SEMANTIC_POS_RATIO)
    parser.add_argument("--ct_bulk_semantic_deep_ratio", type=float, default=CT_BULK_SEMANTIC_DEEP_RATIO)
    parser.add_argument("--ct_bulk_semantic_boundary_ratio", type=float, default=CT_BULK_SEMANTIC_BOUNDARY_RATIO)
    parser.add_argument("--ct_bulk_semantic_cavity_material_ratio", type=float, default=CT_BULK_SEMANTIC_CAVITY_MATERIAL_RATIO)
    parser.add_argument("--ct_bulk_semantic_void_air_ratio", type=float, default=CT_BULK_SEMANTIC_VOID_AIR_RATIO)
    parser.add_argument("--ct_bulk_semantic_cavity_air_ratio", type=float, default=CT_BULK_SEMANTIC_CAVITY_AIR_RATIO)
    parser.add_argument("--ct_bulk_semantic_exterior_air_ratio", type=float, default=CT_BULK_SEMANTIC_EXTERIOR_AIR_RATIO)
    parser.add_argument("--ct_focal_gamma_pos", type=float, default=CT_FOCAL_GAMMA_POS)
    parser.add_argument("--ct_focal_gamma_neg", type=float, default=CT_FOCAL_GAMMA_NEG)
    parser.add_argument("--ct_focal_alpha_pos", type=float, default=CT_FOCAL_ALPHA_POS)
    parser.add_argument("--ct_bulk_semantic_boundary_target", type=float, default=CT_BULK_SEMANTIC_BOUNDARY_TARGET)
    parser.add_argument("--ct_bulk_semantic_cavity_target", type=float, default=CT_BULK_SEMANTIC_CAVITY_TARGET)
    parser.add_argument("--ct_bulk_floor_weight", type=float, default=CT_BULK_FLOOR_WEIGHT)
    parser.add_argument("--ct_bulk_floor_deep_target", type=float, default=CT_BULK_FLOOR_DEEP_TARGET)
    parser.add_argument("--ct_bulk_floor_shell_target", type=float, default=CT_BULK_FLOOR_SHELL_TARGET)
    parser.add_argument("--ct_bulk_void_weight", type=float, default=CT_BULK_VOID_WEIGHT)
    parser.add_argument("--ct_loss_boundary_band_delta", type=float, default=CT_LOSS_BOUNDARY_BAND_DELTA)
    parser.add_argument("--ct_loss_band_in_weight", type=float, default=CT_LOSS_BAND_IN_WEIGHT)
    parser.add_argument("--ct_loss_band_out_weight", type=float, default=CT_LOSS_BAND_OUT_WEIGHT)
    parser.add_argument("--ct_bulk_coverage_weight", type=float, default=CT_BULK_COVERAGE_WEIGHT)
    parser.add_argument("--ct_bulk_coverage_sample_count", type=int, default=CT_BULK_COVERAGE_SAMPLE_COUNT)
    parser.add_argument("--ct_bulk_coverage_target", type=float, default=CT_BULK_COVERAGE_TARGET)
    parser.add_argument("--ct_bulk_air_exclusion_weight", type=float, default=CT_BULK_AIR_EXCLUSION_WEIGHT)
    parser.add_argument("--ct_bulk_air_exclusion_sample_count", type=int, default=CT_BULK_AIR_EXCLUSION_SAMPLE_COUNT)
    parser.add_argument("--ct_bulk_air_exclusion_target", type=float, default=CT_BULK_AIR_EXCLUSION_TARGET)
    parser.add_argument("--ct_cavity_material_coverage_weight", type=float, default=CT_CAVITY_MATERIAL_COVERAGE_WEIGHT)
    parser.add_argument("--ct_cavity_false_hole_boost", type=float, default=CT_CAVITY_FALSE_HOLE_BOOST)
    parser.add_argument("--ct_containment_weight", type=float, default=CT_BULK_SDF_CONTAINMENT_WEIGHT)
    parser.add_argument("--ct_bulk_sdf_containment_sample_count", type=int, default=CT_BULK_SDF_CONTAINMENT_SAMPLE_COUNT)
    parser.add_argument("--ct_bulk_sdf_containment_margin", type=float, default=CT_BULK_SDF_CONTAINMENT_MARGIN)
    parser.add_argument("--ct_init_strategy", type=str, default=CT_INIT_STRATEGY, choices=["volume_sampled", "coverage_first"])
    parser.add_argument("--ct_init_coverage_normalized_atten", action=BooleanOptionalAction, default=CT_INIT_COVERAGE_NORMALIZED_ATTEN)
    parser.add_argument("--ct_init_boundary_inward_nudge", action=BooleanOptionalAction, default=CT_INIT_BOUNDARY_INWARD_NUDGE)
    parser.add_argument("--ct_init_boundary_sigma_c", type=float, default=CT_INIT_BOUNDARY_SIGMA_C)
    parser.add_argument("--ct_init_deep_sigma_voxel", type=float, default=CT_INIT_DEEP_SIGMA_VOXEL)
    parser.add_argument("--ct_init_deep_depth_voxel", type=float, default=CT_INIT_DEEP_DEPTH_VOXEL)
    parser.add_argument("--ct_init_inward_nudge_sigma_ratio", type=float, default=CT_INIT_INWARD_NUDGE_SIGMA_RATIO)
    parser.add_argument("--ct_init_coverage_knn_k", type=int, default=CT_INIT_COVERAGE_KNN_K)
    parser.add_argument("--ct_init_coverage_report", action=BooleanOptionalAction, default=CT_INIT_COVERAGE_REPORT)
    parser.add_argument("--ct_init_coverage_c_min_material", type=float, default=CT_INIT_COVERAGE_C_MIN_MATERIAL)
    parser.add_argument("--ct_init_coverage_c_min_shell", type=float, default=CT_INIT_COVERAGE_C_MIN_SHELL)
    parser.add_argument("--ct_init_coverage_void_epsilon", type=float, default=CT_INIT_COVERAGE_VOID_EPSILON)
    parser.add_argument("--ct_stage1_freeze_until_iter", type=int, default=CT_STAGE1_FREEZE_UNTIL_ITER)
    parser.add_argument("--ct_containment_ramp_iter_1", type=int, default=CT_CONTAINMENT_RAMP_ITER_1)
    parser.add_argument("--ct_containment_ramp_weight_1", type=float, default=CT_CONTAINMENT_RAMP_WEIGHT_1)
    parser.add_argument("--ct_containment_ramp_iter_2", type=int, default=CT_CONTAINMENT_RAMP_ITER_2)
    parser.add_argument("--ct_containment_ramp_weight_2", type=float, default=CT_CONTAINMENT_RAMP_WEIGHT_2)
    parser.add_argument("--ct_containment_ramp_iter_3", type=int, default=CT_CONTAINMENT_RAMP_ITER_3)
    parser.add_argument("--ct_containment_ramp_weight_3", type=float, default=CT_CONTAINMENT_RAMP_WEIGHT_3)
    parser.add_argument("--ct_false_hole_sample_count", type=int, default=CT_FALSE_HOLE_SAMPLE_COUNT)
    parser.add_argument("--ct_false_hole_boundary_band", type=float, default=CT_FALSE_HOLE_BOUNDARY_BAND)
    parser.add_argument("--ct_false_hole_material_threshold", type=float, default=CT_FALSE_HOLE_MATERIAL_THRESHOLD)
    parser.add_argument("--ct_false_hole_dark_margin", type=float, default=CT_FALSE_HOLE_DARK_MARGIN)
    parser.add_argument("--ct_false_hole_target_occupancy", type=float, default=CT_FALSE_HOLE_TARGET_OCCUPANCY)
    parser.add_argument("--ct_false_hole_metrics_interval", type=int, default=CT_FALSE_HOLE_METRICS_INTERVAL)
    parser.add_argument("--ct_bulk_max_scale", type=float, default=2.0)
    parser.add_argument("--ct_bulk_augment_factor", type=float, default=2.0)
    parser.add_argument("--ct_bulk_continuous_init", action=BooleanOptionalAction, default=CT_BULK_CONTINUOUS_INIT)
    parser.add_argument("--ct_bulk_init_mode", type=str, default="sparse_reseed",
                        choices=["sparse_reseed", "contained_lattice", "conservative_envelope", "feature_adaptive", "fasj"],
                        help="bulk initialization mode")
    parser.add_argument("--ct_bulk_lattice_spacing_vox", type=float, default=2.0)
    parser.add_argument("--ct_bulk_lattice_sigma_vox", type=float, default=2.0)
    parser.add_argument("--ct_bulk_lattice_margin_vox", type=float, default=0.05)
    parser.add_argument("--ct_bulk_lattice_atten_init", type=float, default=0.75)
    parser.add_argument("--ct_bulk_lattice_anisotropic", action=BooleanOptionalAction, default=False)
    parser.add_argument("--ct_bulk_lattice_sigma_t_vox", type=float, default=2.0)
    parser.add_argument("--ct_bulk_lattice_sigma_n_vox", type=float, default=0.8)
    parser.add_argument("--ct_feature_adaptive_jitter", action=BooleanOptionalAction, default=CT_FEATURE_ADAPTIVE_JITTER)
    parser.add_argument("--ct_feature_adaptive_seed", type=int, default=CT_FEATURE_ADAPTIVE_SEED)
    parser.add_argument("--ct_feature_adaptive_r_shell_vox", type=float, default=CT_FEATURE_ADAPTIVE_R_SHELL_VOX)
    parser.add_argument("--ct_feature_adaptive_blur_sigma_vox", type=float, default=CT_FEATURE_ADAPTIVE_BLUR_SIGMA_VOX)
    parser.add_argument("--ct_feature_adaptive_spacing_high_vox", type=int, default=CT_FEATURE_ADAPTIVE_SPACING_HIGH_VOX)
    parser.add_argument("--ct_feature_adaptive_spacing_mid_vox", type=int, default=CT_FEATURE_ADAPTIVE_SPACING_MID_VOX)
    parser.add_argument("--ct_feature_adaptive_spacing_low_vox", type=int, default=CT_FEATURE_ADAPTIVE_SPACING_LOW_VOX)
    parser.add_argument(
        "--ct_feature_adaptive_directional_clearance",
        action=BooleanOptionalAction,
        default=CT_FEATURE_ADAPTIVE_DIRECTIONAL_CLEARANCE,
    )
    parser.add_argument("--ct_feature_adaptive_probe_containment", action=BooleanOptionalAction, default=CT_FEATURE_ADAPTIVE_PROBE_CONTAINMENT)
    parser.add_argument("--ct_bulk_containment_q_support", type=float, default=CT_BULK_CONTAINMENT_Q_SUPPORT)
    parser.add_argument("--ct_bulk_query_truncation_sigma", type=float, default=None)
    parser.add_argument("--ct_init_preflight_abort", action=BooleanOptionalAction, default=CT_INIT_PREFLIGHT_ABORT)
    parser.add_argument("--ct_init_preflight_max_containment_violation", type=float, default=CT_INIT_PREFLIGHT_MAX_CONTAINMENT_VIOLATION)
    parser.add_argument("--ct_init_preflight_min_material_a_b_p10", type=float, default=CT_INIT_PREFLIGHT_MIN_MATERIAL_A_B_P10)
    parser.add_argument("--ct_init_preflight_max_material_coverage_gap", type=float, default=CT_INIT_PREFLIGHT_MAX_MATERIAL_COVERAGE_GAP)
    parser.add_argument("--ct_bulk_coverage_gap_threshold", type=float, default=CT_BULK_COVERAGE_GAP_THRESHOLD)
    parser.add_argument("--ct_freeze_bulk_xyz", action=BooleanOptionalAction, default=CT_FREEZE_BULK_XYZ)
    parser.add_argument("--ct_freeze_surface", action=BooleanOptionalAction, default=CT_FREEZE_SURFACE)
    parser.add_argument("--ct_freeze_bulk_geometry", action=BooleanOptionalAction, default=CT_FREEZE_BULK_GEOMETRY)
    parser.add_argument("--ct_train_bulk_atten_only", action=BooleanOptionalAction, default=CT_TRAIN_BULK_ATTEN_ONLY)
    parser.add_argument("--ct_enable_surface_reseeding", action=BooleanOptionalAction, default=True)
    parser.add_argument("--ct_enable_densification", action=BooleanOptionalAction, default=True)
    parser.add_argument("--ct_densify_from_iter", type=int, default=CT_DENSIFY_FROM_ITER)
    parser.add_argument("--ct_densify_until_iter", type=int, default=CT_DENSIFY_UNTIL_ITER)
    parser.add_argument("--ct_densify_interval", type=int, default=CT_DENSIFY_INTERVAL)
    parser.add_argument("--ct_densify_surface_percent", type=float, default=CT_DENSIFY_SURFACE_PERCENT)
    parser.add_argument("--ct_densify_bulk_percent", type=float, default=CT_DENSIFY_BULK_PERCENT)
    parser.add_argument("--ct_densify_max_gaussian_ratio", type=float, default=CT_DENSIFY_MAX_GAUSSIAN_RATIO)
    parser.add_argument("--ct_densify_min_opacity", type=float, default=CT_DENSIFY_MIN_OPACITY)
    parser.add_argument("--ct_densify_surface_tangent_ratio", type=float, default=CT_DENSIFY_SURFACE_TANGENT_RATIO)
    parser.add_argument("--ct_densify_bulk_scale_ratio", type=float, default=CT_DENSIFY_BULK_SCALE_RATIO)
    parser.add_argument("--ct_enable_bulk_reseeding", action=BooleanOptionalAction, default=True)
    parser.add_argument("--ct_bulk_reseed_from_iter", type=int, default=500)
    parser.add_argument("--ct_bulk_reseed_until_iter", type=int, default=4000)
    parser.add_argument("--ct_bulk_reseed_interval", type=int, default=500)
    parser.add_argument("--ct_bulk_reseed_sample_count", type=int, default=8192)
    parser.add_argument("--ct_bulk_reseed_max_per_iter", type=int, default=0)
    parser.add_argument("--ct_bulk_reseed_max_new_fraction", type=float, default=0.03)
    parser.add_argument("--ct_bulk_reseed_max_gaussian_ratio", type=float, default=2.5)
    parser.add_argument("--ct_bulk_reseed_occupancy_threshold", type=float, default=0.85)
    parser.add_argument("--ct_bulk_reseed_min_sdf_margin", type=float, default=-0.2)
    parser.add_argument("--ct_bulk_reseed_initial_opacity", type=float, default=0.65)
    parser.add_argument("--ct_gap_aware_reseed", action=BooleanOptionalAction, default=CT_GAP_AWARE_RESEED)
    parser.add_argument("--ct_gap_reseed_den_target", type=float, default=CT_GAP_RESEED_DEN_TARGET)
    parser.add_argument("--ct_gap_reseed_sample_ratio", type=float, default=CT_GAP_RESEED_SAMPLE_RATIO)
    parser.add_argument("--ct_gap_reseed_radius_vox", type=float, default=CT_GAP_RESEED_RADIUS_VOX)
    parser.add_argument("--ct_gap_reseed_max_per_iter", type=int, default=CT_GAP_RESEED_MAX_PER_ITER)
    parser.add_argument("--ct_gap_reseed_boundary_subvoxel", action=BooleanOptionalAction, default=CT_GAP_RESEED_BOUNDARY_SUBVOXEL)
    parser.add_argument("--ct_gap_reseed_protect_prune", action=BooleanOptionalAction, default=CT_GAP_RESEED_PROTECT_PRUNE)
    parser.add_argument("--ct_gap_reseed_protect_iters", type=int, default=CT_GAP_RESEED_PROTECT_ITERS)
    parser.add_argument("--ct_gap_bulk_growth_factor", type=float, default=CT_GAP_BULK_GROWTH_FACTOR)
    parser.add_argument("--ct_budgeted_component_repair", action=BooleanOptionalAction, default=CT_BUDGETED_COMPONENT_REPAIR)
    parser.add_argument("--ct_repair_add_threshold", type=float, default=CT_REPAIR_ADD_THRESHOLD)
    parser.add_argument("--ct_repair_stop_threshold", type=float, default=CT_REPAIR_STOP_THRESHOLD)
    parser.add_argument("--ct_repair_min_component_points", type=int, default=CT_REPAIR_MIN_COMPONENT_POINTS)
    parser.add_argument("--ct_repair_max_new_per_pass", type=int, default=CT_REPAIR_MAX_NEW_PER_PASS)
    parser.add_argument("--ct_repair_max_new_fraction", type=float, default=CT_REPAIR_MAX_NEW_FRACTION)
    parser.add_argument("--ct_repair_gain_ratio_min", type=float, default=CT_REPAIR_GAIN_RATIO_MIN)
    parser.add_argument("--ct_repair_exclusion_radius_vox", type=float, default=CT_REPAIR_EXCLUSION_RADIUS_VOX)
    parser.add_argument("--ct_repair_stretch_first", action=BooleanOptionalAction, default=CT_REPAIR_STRETCH_FIRST)
    parser.add_argument("--ct_repair_stretch_growth_factor", type=float, default=CT_REPAIR_STRETCH_GROWTH_FACTOR)
    parser.add_argument("--ct_repair_stretch_secondary_factor", type=float, default=CT_REPAIR_STRETCH_SECONDARY_FACTOR)
    parser.add_argument("--ct_repair_stretch_max_ratio", type=float, default=CT_REPAIR_STRETCH_MAX_RATIO)
    parser.add_argument("--ct_repair_overfill_threshold", type=float, default=CT_REPAIR_OVERFILL_THRESHOLD)
    parser.add_argument("--ct_repair_top_components", type=int, default=CT_REPAIR_TOP_COMPONENTS)
    parser.add_argument("--ct_repair_nearby_candidates", type=int, default=CT_REPAIR_NEARBY_CANDIDATES)
    parser.add_argument("--ct_repair_probe_tangent_factor", type=float, default=CT_REPAIR_PROBE_TANGENT_FACTOR)
    parser.add_argument("--ct_repair_probe_shrink", type=float, default=CT_REPAIR_PROBE_SHRINK)
    parser.add_argument("--ct_repair_max_probe_shrink_iters", type=int, default=CT_REPAIR_MAX_PROBE_SHRINK_ITERS)
    parser.add_argument("--ct_repair_check_stride", type=int, default=CT_REPAIR_CHECK_STRIDE)
    parser.add_argument("--ct_repair_max_check_points", type=int, default=CT_REPAIR_MAX_CHECK_POINTS)
    parser.add_argument("--ct_material_coverage_completion", action=BooleanOptionalAction, default=CT_MATERIAL_COVERAGE_COMPLETION)
    parser.add_argument("--ct_completion_init", action=BooleanOptionalAction, default=CT_COMPLETION_INIT)
    parser.add_argument("--ct_completion_repair", action=BooleanOptionalAction, default=CT_COMPLETION_REPAIR)
    parser.add_argument("--ct_completion_den_target", type=float, default=CT_COMPLETION_DEN_TARGET)
    parser.add_argument("--ct_completion_radius_vox", type=float, default=CT_COMPLETION_RADIUS_VOX)
    parser.add_argument("--ct_completion_max_init_passes", type=int, default=CT_COMPLETION_MAX_INIT_PASSES)
    parser.add_argument("--ct_completion_max_new_per_pass", type=int, default=CT_COMPLETION_MAX_NEW_PER_PASS)
    parser.add_argument("--ct_completion_min_component_voxels", type=int, default=CT_COMPLETION_MIN_COMPONENT_VOXELS)
    parser.add_argument("--ct_completion_check_stride", type=int, default=CT_COMPLETION_CHECK_STRIDE)
    parser.add_argument("--ct_completion_max_check_points", type=int, default=CT_COMPLETION_MAX_CHECK_POINTS)
    parser.add_argument("--ct_sdf_boundary_mode", type=str, default=CT_SDF_BOUNDARY_MODE)
    parser.add_argument("--ct_reseed_probe_length", type=float, default=CT_RESEED_PROBE_LENGTH)
    parser.add_argument("--ct_reseed_band_deficit_thr", type=float, default=CT_RESEED_BAND_DEFICIT_THR)
    parser.add_argument("--ct_reseed_seed_offset_sigma", type=float, default=CT_RESEED_SEED_OFFSET_SIGMA)
    parser.add_argument("--ct_reseed_max_new_fraction", type=float, default=CT_RESEED_MAX_NEW_FRACTION)
    parser.add_argument("--ct_reseed_sigma_init_factor", type=float, default=CT_RESEED_SIGMA_INIT_FACTOR)
    parser.add_argument("--ct_reseed_sigma_init_floor_ratio", type=float, default=CT_RESEED_SIGMA_INIT_FLOOR_RATIO)
    parser.add_argument("--ct_reseed_atten_init_boost", type=float, default=CT_RESEED_ATTEN_INIT_BOOST)
    parser.add_argument("--ct_bulk_prune_interval", type=int, default=CT_BULK_PRUNE_INTERVAL)
    parser.add_argument("--ct_bulk_prune_warmup", type=int, default=CT_BULK_PRUNE_WARMUP)
    parser.add_argument("--ct_bulk_prune_min_opacity", type=float, default=CT_BULK_PRUNE_MIN_OPACITY)
    parser.add_argument("--ct_bulk_prune_air_sdf_epsilon", type=float, default=CT_BULK_PRUNE_AIR_SDF_EPSILON)
    parser.add_argument("--ct_bulk_prune_raw_air_threshold", type=float, default=CT_BULK_PRUNE_RAW_AIR_THRESHOLD)
    parser.add_argument("--ct_bulk_prune_sample_count", type=int, default=CT_BULK_PRUNE_SAMPLE_COUNT)
    parser.add_argument("--ct_bulk_prune_neighbor_radius", type=float, default=CT_BULK_PRUNE_NEIGHBOR_RADIUS)
    parser.add_argument("--ct_bulk_prune_min_neighbors", type=int, default=CT_BULK_PRUNE_MIN_NEIGHBORS)
    parser.add_argument("--ct_intensity_phase2_start_ratio", type=float, default=CT_INTENSITY_PHASE2_START_RATIO)
    parser.add_argument("--ct_intensity_phase3_start_ratio", type=float, default=CT_INTENSITY_PHASE3_START_RATIO)
    parser.add_argument("--ct_intensity_train_bulk_scale", action=BooleanOptionalAction, default=CT_INTENSITY_TRAIN_BULK_SCALE)
    parser.add_argument("--ct_intensity_train_surface_opacity", action=BooleanOptionalAction, default=CT_INTENSITY_TRAIN_SURFACE_OPACITY)
    parser.add_argument("--ct_intensity_bulk_scale_grad", type=float, default=CT_INTENSITY_BULK_SCALE_GRAD)
    parser.add_argument("--ct_intensity_sample_mode", type=str, default=CT_INTENSITY_SAMPLE_MODE, choices=["full_band", "material_interior_only"])
    parser.add_argument("--ct_intensity_erode_margin_vox", type=float, default=CT_INTENSITY_ERODE_MARGIN_VOX)
    parser.add_argument("--ct_intensity_den_min", type=float, default=CT_INTENSITY_DEN_MIN)
    parser.add_argument("--ct_atten_only_train_bulk_opacity", action=BooleanOptionalAction, default=CT_ATTEN_ONLY_TRAIN_BULK_OPACITY)
    parser.add_argument("--ct_bulk_opacity_sparse_weight", type=float, default=CT_BULK_OPACITY_SPARSE_WEIGHT)
    parser.add_argument("--ct_atten_only_lr_final_scale", type=float, default=CT_ATTEN_ONLY_LR_FINAL_SCALE)
    parser.add_argument("--ct_atten_only_early_stop", action=BooleanOptionalAction, default=CT_ATTEN_ONLY_EARLY_STOP)
    parser.add_argument("--ct_atten_only_early_stop_warmup_iters", type=int, default=CT_ATTEN_ONLY_EARLY_STOP_WARMUP_ITERS)
    parser.add_argument("--ct_atten_only_early_stop_eval_interval", type=int, default=CT_ATTEN_ONLY_EARLY_STOP_EVAL_INTERVAL)
    parser.add_argument("--ct_atten_only_early_stop_patience", type=int, default=CT_ATTEN_ONLY_EARLY_STOP_PATIENCE)
    parser.add_argument("--ct_atten_only_early_stop_min_delta", type=float, default=CT_ATTEN_ONLY_EARLY_STOP_MIN_DELTA)
    parser.add_argument("--ct_eagle_loss_weight", type=float, default=CT_EAGLE_LOSS_WEIGHT)
    parser.add_argument("--ct_eagle_patch_size", type=int, default=CT_EAGLE_PATCH_SIZE)
    parser.add_argument("--ct_eagle_block_size", type=int, default=CT_EAGLE_BLOCK_SIZE)
    parser.add_argument("--ct_auto_preview", action=BooleanOptionalAction, default=True)
    parser.add_argument("--ct_preview_first_iter", action=BooleanOptionalAction, default=True)
    parser.add_argument("--ct_preview_interval", type=int, default=CT_PREVIEW_INTERVAL)
    parser.add_argument("--output_gs", type=str, default=None)
    parser.add_argument("--output_mesh", type=str, default=None)
    parser.add_argument("--output_sdf", type=str, default=None)
    parser.add_argument("--export_mesh_resolution", type=float, default=0.05)
    parser.add_argument("--export_sdf_resolution", type=int, default=256)
    parser.add_argument("--skip_export_mesh", action="store_true", default=False)
    parser.add_argument("--skip_export_sdf", action="store_true", default=False)
    return parser
