from __future__ import annotations

from ct_pipeline.training.objectives.context import CTLossTerms
from ct_pipeline.training.objectives.modes import (
    _boundary_band_distance,
    _bulk_halfspace_tau_current,
    _bulk_intensity_sample_mode,
    _bulk_intensity_training_enabled,
    _containment_ramp_weight,
    _dual_separated_training_enabled,
    _dual_surface_air_band,
    _dual_surface_inner_band,
    _intensity_geometry_flags,
    _surface_material_render_band,
    _use_unified_compositor,
)
from ct_pipeline.training.objectives.prediction import (
    _bulk_intensity_from_fields,
    _bulk_intensity_prediction,
    compute_raw_combined_ct_occupancy,
    compute_role_separated_ct_prediction,
    compute_surface_bounded_bulk_volume_prediction,
)
from ct_pipeline.training.objectives.sampling import (
    _phase_mask_from_analysis,
    _phase_occupancy_sdf_weights,
    _sample_air_points_with_void_bias,
    _sample_boundary_offset_shell_points,
    _sample_filtered_from_candidate_sets,
    _sample_filtered_semantic_points,
    _sample_support_membership,
    _split_phase_occupancy_sample_counts,
    _support_mask_from_analysis,
    _support_membership_gate,
)

__all__ = [
    "CTLossTerms",
    "_boundary_band_distance",
    "_bulk_halfspace_tau_current",
    "_bulk_intensity_from_fields",
    "_bulk_intensity_prediction",
    "_bulk_intensity_sample_mode",
    "_bulk_intensity_training_enabled",
    "_containment_ramp_weight",
    "_dual_separated_training_enabled",
    "_dual_surface_air_band",
    "_dual_surface_inner_band",
    "_intensity_geometry_flags",
    "_phase_mask_from_analysis",
    "_phase_occupancy_sdf_weights",
    "_sample_air_points_with_void_bias",
    "_sample_boundary_offset_shell_points",
    "_sample_filtered_from_candidate_sets",
    "_sample_filtered_semantic_points",
    "_sample_support_membership",
    "_surface_material_render_band",
    "_split_phase_occupancy_sample_counts",
    "_support_mask_from_analysis",
    "_support_membership_gate",
    "_use_unified_compositor",
    "compute_raw_combined_ct_occupancy",
    "compute_role_separated_ct_prediction",
    "compute_surface_bounded_bulk_volume_prediction",
]
